import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { LoginProvider } from "./components/reactContext/LoginProvider";
import { ThemeProvider } from "./components/reactContext/ThemeProvider";
import { Providers } from "@/function/redux/provider";
import { CategoryProvider } from "./components/reactContext/categoryProvider";
import SearchProvider from "./components/reactContext/searchProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-slate-50 dark:bg-slate-950 transition-colors">
        <Providers>
          <LoginProvider>
            <ThemeProvider>
              <CategoryProvider>
                <SearchProvider>
                  {children}
                </SearchProvider>
              </CategoryProvider>
            </ThemeProvider>
          </LoginProvider>
        </Providers>
      </body>
    </html>
  );
}
